### PR TITLE
2459 unparsing unresolved behavior annexes

### LINKED ISSUE #2459: Support unparsing when behavior annex has resolution errors
Update OSATE and the behavior annex plugin to support accessing and unparsing of any parsed behavior annex regardless of resolution issues. This is helpful for the graphical editor to allow editing behavior annex subclauses when there are resolution or legality errors.

# Parsed annex sublause is null whenever a resolution error occurs.
The parsed annex subclause is set to  null if there are any resolution errors. This behavior should be removed by removing the following lines from `AnnexParserAgent`
```
if (resolveErrReporter.getNumErrors() != 0) {
	setParsedAnnexSection.accept(null);
}
```

# Unparsing fails in some cases
In some cases the behavior annex unparser fails and produces unexpected results. Given the following model:

```aadl
package ba_unparse
public

	system top
	annex behavior_specification {**
		states
			s3 : state;
		transitions
            t1 : s1 -[]-> s2 {
              o1 := tmp + 1
            };
        **};
end top;
	
end ba_unparse;
```

Adding a new state and unparsing with the graphical editor and unparsing produces:

```aadlpackage ba_unparse
public

	system top
	annex behavior_specification {**
          states
            s3 : state;
            top_new_state : initial state;
          transitions
        **};
end top;
	
end ba_unparse;
```

The following message appears in the console of the development environment: `aadlba unparsing failed for : DeclarativeBehaviorTransitionImpl`

There may be other unparsing cases that are problematic but these are the ones we have experienced so far.
@RyanMcilnay  please add comments with any other cases where unparsing fails. You'll need to make the change to `AnnexParserAgent` first.

### PR DESCRIPTION
**Pull request by Etienne13**
fixes #2459 while preserving the fix of #1863 by adding inhibiting EMF validation in case of parsing or resolution errors

### CODE REVIEW

**Comment by lwrage** [comment]
@Etienne13 Could you reformat using the OSATE code formatting profile and remove any commented out lines of code, please?

**Comment by Etienne13** [comment]
@lwrage sure, I thought my editor does the OSATE formatting automatically and I did not notice Dominique's setup was different. Can you confirm the formatting of my editor (used for ma latest commit) does enforce the same formatting as OSATE? Otherwise, how should I proceed?

Note: I had to add a new class cause the formatter was producing a code that did not compile.

I am willing to use the same formatting for the BA implementation; Actually, I thought it was already the case. Maybe I missed something on this topic.

**Comment by philip-alldredge** [comment]
@lwrage I adjusted the reviewer to @RyanMcilnay since he is in a better position to determine whether this resolves the issue.

**Review by RyanMcilnay — DISMISSED** [review]

**Comment by RyanMcilnay** [comment]
@Etienne13  There does seem to be a problem related to these changes.  I am receiving a NullPointerException when trying to use the refactor "Rename Element" if an error occurs in a BehaviorAnnex in the text editor.

.

Steps to reproduce:
1. Copy the code below into the text editor
2. Right click on bus B
3. Select "Rename Element"

````
package test
public
with Base_Types;

	abstract A
	    modes
		M: initial mode;
            annex behavior_specification {**
                variables
                    V : Base_Types::Character;
                states
                    M : initial state;
            **};
	end A;
	
	bus B
	end B;
end test;
````

Stacktrace:
````
java.lang.NullPointerException
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eURIFragmentSegment(BasicEObjectImpl.java:292)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.getURIFragment(ResourceImpl.java:679)
	at org.eclipse.xtext.resource.XtextResource.access$001(XtextResource.java:63)
	at org.eclipse.xtext.resource.XtextResource$1.getFragment(XtextResource.java:114)
	at org.osate.xtext.aadl2.util.Aadl2QualifiedNameFragmentProvider.getFragment(Aadl2QualifiedNameFragmentProvider.java:63)
	at org.eclipse.xtext.resource.XtextResource.getURIFragment(XtextResource.java:373)
	at org.eclipse.emf.ecore.util.EcoreUtil.getURI(EcoreUtil.java:3071)
	at org.eclipse.xtext.EcoreUtil2.getPlatformResourceOrNormalizedURI(EcoreUtil2.java:620)
	at org.osate.xtext.aadl2.findReferences.Aadl2ReferenceFinder.findLocalReferencesFromElement(Aadl2ReferenceFinder.java:96)
	at org.osate.xtext.aadl2.findReferences.Aadl2ReferenceFinder.findLocalReferencesFromElement(Aadl2ReferenceFinder.java:64)
	at org.osate.xtext.aadl2.findReferences.Aadl2ReferenceFinder.findLocalReferencesFromElement(Aadl2ReferenceFinder.java:70)
	at org.osate.xtext.aadl2.findReferences.Aadl2ReferenceFinder.findLocalReferencesFromElement(Aadl2ReferenceFinder.java:64)
	at org.osate.xtext.aadl2.findReferences.Aadl2ReferenceFinder.findLocalReferencesFromElement(Aadl2ReferenceFinder.java:64)
	at org.osate.xtext.aadl2.findReferences.Aadl2ReferenceFinder.findLocalReferencesFromElement(Aadl2ReferenceFinder.java:70)
	at org.eclipse.xtext.findReferences.ReferenceFinder.findReferences(ReferenceFinder.java:139)
	at org.eclipse.xtext.findReferences.ReferenceFinder.findReferences(ReferenceFinder.java:125)
	at org.eclipse.xtext.ui.refactoring.ui.DefaultLinkedPositionGroupCalculator.getLinkedPositionGroup(DefaultLinkedPositionGroupCalculator.java:169)
	at org.eclipse.xtext.ui.refactoring.ui.RenameRefactoringController$1.run(RenameRefactoringController.java:146)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
````

**Comment by Etienne13** [comment]
@RyanMcilnay I think I have found what causes this problem but I am not sure yet how to fix it with a clean solution.

**Comment by Etienne13** [comment]
@RyanMcilnay my last changes fix the problem you mentioned. I tried to find the root cause and fix it. Can you try it again and let me know if you find other bugs?

**Comment by RyanMcilnay** [comment]
@Etienne13 Great!  Yeah, I will continue testing.  Thank you.

**Review by RyanMcilnay — APPROVED** [review]

**Pull request merged**
