### PR TITLE
Include graphical editor EMV2 plugin with releases

### LINKED ISSUE #2450: Visualization and editing capability for EMV2 flow propagations
- [x] Enable automated tests
- [x] Promote to non-experimental
- [ ] Ensure it is included in code coverage.

### PR DESCRIPTION
**Pull request by philip-alldredge**
Closes #2450

### CODE REVIEW

**Comment by philip-alldredge** [comment]
@lwrage the build for this draft pull request is failing? Can you take a look at it or is there a way to build such that it would be easier to find the error? The tests that are failing do not fail locally.  I built a maven build locally and ran into an error  in the error log while trying to do the steps manually. However, once I did a clean/local maven build, the issue resolved itself. The intention of the pull request is to make the error model plugin/feature available as part of the normal build. It looks like the plugin is running in the test environment but there is something happening that is causing the failure.  Are there any additional log files from the test environment workspace that can be viewed?

**Comment by lwrage** [comment]
In Jenkins you can only see the console output and the test log files. The test log file (only contains the full error message:

```
------------------------------------------------------------------------------
Test set: org.osate.ge.tests.endToEnd.ErrorModelTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 34.169 s <<< FAILURE! - in org.osate.ge.tests.endToEnd.ErrorModelTest
testErrorModelLibrary(org.osate.ge.tests.endToEnd.ErrorModelTest)  Time elapsed: 21.022 s  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 10000 ms.: Expected element '[[package, emv2_test],[emv2.error_type, new_error_type]]' doesn't exist.
	at org.osate.ge.tests.endToEnd.ErrorModelTest.testErrorModelLibrary(ErrorModelTest.java:77)

testErrorFlows(org.osate.ge.tests.endToEnd.ErrorModelTest)  Time elapsed: 13.066 s  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 10000 ms.: Expected element '[[package, error_flow_test],[classifier, subsystem.impl],[emv2.propagation_point, subsystem_impl_new_propagation_point]]' doesn't exist.
	at org.osate.ge.tests.endToEnd.ErrorModelTest.testErrorFlows(ErrorModelTest.java:374)
```

Maybe you could create screenshots with `bot.captureScreenshot(filename)` right before the errors to see what's on the screen.

Other options don't work: Xvnc screenshot happens after eclipse has closed down, so that's out. VncRecorder jenkins plugin requires vnc2swf, which is not available for installation on osate-build. VncViewer jenkins plugin requires access to port that is blocked by the firewall.

**Comment by philip-alldredge** [comment]
I added some code to print the Eclipse log to the console temporarily. The results are below. I've already reverted the temporary logging code. 

From the results, it looks like we are hitting this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=566490 

Can you add the suggested workaround to the test environment until we update Eclipse again?


> !ENTRY org.eclipse.urischeme 4 0 2020-11-13 08:36:29.559
> !MESSAGE 
> !STACK 0
> java.lang.NullPointerException
> 	at org.eclipse.urischeme.internal.registration.DesktopFileWriter.escapeSpaces(DesktopFileWriter.java:186)
> 	at org.eclipse.urischeme.internal.registration.DesktopFileWriter.getMinimalDesktopFileContent(DesktopFileWriter.java:175)
> 	at org.eclipse.urischeme.internal.registration.RegistrationLinux.readFileOrGetInitialContent(RegistrationLinux.java:107)
> 	at org.eclipse.urischeme.internal.registration.RegistrationLinux.changeDesktopFile(RegistrationLinux.java:90)
> 	at org.eclipse.urischeme.internal.registration.RegistrationLinux.handleSchemes(RegistrationLinux.java:56)
> 	at org.eclipse.urischeme.AutoRegisterSchemeHandlersJob.run(AutoRegisterSchemeHandlersJob.java:70)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> 
> !ENTRY org.eclipse.ui.views.properties.tabbed 4 4 2020-11-13 08:36:30.608
> !MESSAGE Contributor org.osate.ui.navigator.AadlNavigator cannot be created.
> 
> !ENTRY org.osate.annexsupport 4 0 2020-11-13 08:36:35.925
> !MESSAGE Failed to instantiate EMV2 parser org.osate.xtext.aadl2.errormodel.parsing.EMV2AnnexParser in type: org.osate.aadl2.emv2.parser in plugin org.osate.xtext.aadl2.errormodel
> !STACK 1
> org.eclipse.core.runtime.CoreException: Plug-in "org.osate.xtext.aadl2.errormodel" was unable to instantiate class "org.osate.xtext.aadl2.errormodel.parsing.EMV2AnnexParser".
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:206)
> 	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:923)
> 	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
> 	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
> 	at org.osate.annexsupport.AnnexParserProxy.getParser(AnnexParserProxy.java:96)
> 	at org.osate.annexsupport.AnnexParserProxy.parseAnnexLibrary(AnnexParserProxy.java:57)
> 	at org.osate.xtext.aadl2.parsing.AnnexParserAgent.processAnnexSection(AnnexParserAgent.java:196)
> 	at org.osate.xtext.aadl2.parsing.AnnexParserAgent.afterModelLinked(AnnexParserAgent.java:116)
> 	at org.eclipse.xtext.linking.impl.AbstractCleaningLinker.linkModel(AbstractCleaningLinker.java:57)
> 	at org.eclipse.xtext.resource.XtextResource.doLinking(XtextResource.java:340)
> 	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLinking(LazyLinkingResource.java:121)
> 	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:301)
> 	at org.eclipse.xtext.resource.DerivedStateAwareResource.updateInternalState(DerivedStateAwareResource.java:170)
> 	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:290)
> 	at org.eclipse.xtext.resource.DerivedStateAwareResource.updateInternalState(DerivedStateAwareResource.java:162)
> 	at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:180)
> 	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.doLoad(LazyLinkingResource.java:114)
> 	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1563)
> 	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1342)
> 	at org.eclipse.xtext.resource.persistence.StorageAwareResource.load(StorageAwareResource.java:79)
> 	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
> 	at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
> 	at org.eclipse.xtext.resource.XtextResourceSet.getResource(XtextResourceSet.java:265)
> 	at org.eclipse.xtext.resource.SynchronizedXtextResourceSet.getResource(SynchronizedXtextResourceSet.java:25)
> 	at org.eclipse.xtext.builder.resourceloader.SerialResourceLoader$1.next(SerialResourceLoader.java:47)
> 	at org.eclipse.xtext.builder.resourceloader.AbstractResourceLoader$CheckedLoadOperation.next(AbstractResourceLoader.java:80)
> 	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.writeNewResourceDescriptions(ClusteringBuilderState.java:378)
> 	at org.eclipse.xtext.builder.clustering.ClusteringBuilderState.doUpdate(ClusteringBuilderState.java:139)
> 	at org.eclipse.xtext.builder.builderState.AbstractBuilderState.update(AbstractBuilderState.java:152)
> 	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:387)
> 	at org.eclipse.xtext.builder.impl.XtextBuilder.addInfosFromTaskAndBuild(XtextBuilder.java:321)
> 	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:428)
> 	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:201)
> 	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
> 	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
> 	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
> 	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
> 	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
> 	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
> 	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: java.lang.reflect.InvocationTargetException
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:204)
> 	... 44 more
> 

Full Log:
https://osate-build.sei.cmu.edu/jenkins/blue/rest/organizations/jenkins/pipelines/p-OSATE2-PR-Build/branches/PR-2514/runs/13/nodes/13/steps/18/log/?start=0
Entries dumped from eclipse workspace log are prefixed with "GE LOG DUMP:".

**Comment by philip-alldredge** [comment]
@lwrage thanks for finding the issue!

**Review by RyanMcilnay — APPROVED** [review]

**Pull request merged**
