### PR TITLE
Fixed classifier information view to show flow specs in classifier impls

### LINKED ISSUE #2472: Classifier information view doesn't show unimplemented flow specifications
## Summary

If a component type C has a flow specification but it is not implemented in C.i then it is not shown i when C.i is displayed in the classifier information view.

## Expected and Current Behavior

Unimplemented flow specs should be shown, with an indication that they are from the type.

## Steps to Reproduce

1. Open the model below in the AADL text editor
2. In the outline view select a2.i > right click > Show in classifier information view
3. Note that fsource20 and fsink1 don't show up

```aadl
package p
public
		abstract a2
		features
			af2: feature;
			da2: provides data access;
		flows
			fsource20: flow source af2;
			fsink1: flow sink af2;
	end a2;

	abstract implementation a2.i
		subcomponents
			asub3: abstract a2;
		connections
			fconn3: feature af2 -> asub3.af2;
			fconn4: feature asub3.af2 -> asub3.af2;
		flows
			etef18: end to end flow asub3.fsource20 -> fconn4 -> asub3.fsink1;
	end a2.i;
	
end p;
```

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: all

### PR DESCRIPTION
**Pull request by AaronGreenhouse**
Fixed #2472

### CODE REVIEW

**Review by lwrage — CHANGES_REQUESTED** [review]
Works if the implementation has at least one flow implementation (`sys.i1`) but not if the implementation has no flow implementations (`sys.i2`):

```
package i2472
public
	system sys
		features
			i: in data port;
		flows
			fsnk: flow sink i;
			fsnk1: flow sink i;
	end sys;

	system implementation sys.i1
		flows
			fsnk: flow sink i;
	end sys.i1;

	system implementation sys.i2
	end sys.i2;

end i2472;
```

**Comment by AaronGreenhouse** [comment]
> Works if the implementation has at least one flow implementation (`sys.i1`) but not if the implementation has no flow implementations (`sys.i2`):

Fixed this.  I forgot to update the logic for the conditional that controls whether the flows section is added.

**Comment by lwrage** [comment]
@AaronGreenhouse Could you fix the merge conflict, please?

**Comment by AaronGreenhouse** [comment]
> @AaronGreenhouse Could you fix the merge conflict, please?

Fixed

**Review by lwrage — APPROVED** [review]

**Pull request merged**
