### PR TITLE
2611 update icons

### LINKED ISSUE #2605: Wrong icons for calls and parameter connections
**Summary**
The outline view shows a generic icon for calls and parameter connections.

It should use an oval for calls and a line with a P on top for parameter connections.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OSATE Version: 2.9.1
 - Operating System: Linux

### LINKED ISSUE #2611: Update icons
**Please describe the problem your proposed feature would address**
Icons do not scale properly (appear too little on high resolution screens)
Missing icons
Need new icons for outline elements

Example: 
New icons -> parameter connection (icon should look like a line and a letter)

**What is the impact of the problem?**
Affects all OSATE users

Example: 

**Describe the solution you'd like**
Communication Services are working on new icons for MBE team

**Describe alternatives you've considered**
Icons have been altered before via [https://www.pixilart.com/draw/ ](https://www.pixilart.com/draw/ ) 
However, can not produce good quality image with this software

### PR DESCRIPTION
**Pull request by asazonova**
update images 
fixes #2611 
fixes #2605

### CODE REVIEW

**Comment by asazonova** [comment]
@jjhugues ,

please review new icons with this code branch. see test AADL examples above

**Comment by asazonova** [comment]
@lwrage, just reviewed the images with Jerome (no changes requested). could you please test on windows

**Comment by lwrage** [comment]
The icons are mostly fine. I'd like to se a couple of small improvements:

- The S (subcomponent) looks more like an 8 or a B to me. That should be fixed.
- The images for device, processor, and virtual processor could be one pixel wider to allow one additional pixel white space to the right of the letter.
- There are various component prototype categories missing in the example model, e.g., thread prototype.
- There are no feature prototypes in the example model, so I don't know what those look like.
- The A decoration in the navigator doesn't look that good. It's too wide, the "legs" are too short, so it's hard to see that it's a an A.

**Comment by lwrage** [comment]
new icons merged manually in 47843a4c28029a6e9ba7a83be3b703266b97ea74

**Pull request closed without merging**
