### PR TITLE
2442 shorten labels in outline

### LINKED ISSUE #2442: No distinction between flow source/path/sink in outline view
## Summary

The labels in the outline view do not differ for flow source, sink, and path.

## Expected and Current Behavior

All flow source, sink, and path specifications are labeled _Flow Specification_, and all flow source, sink, and path implementations are labeled _Flow Implementation_. It should be _Flow Source_, _Flow Sink_, and _Flow Path_, instead.
  
## Steps to Reproduce

1. Open the model from [issue 2416](https://github.com/osate/osate2/issues/2441) in the text editor
2. Expand `abstract implementation A,i` in the outline view.

image

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: all

### PR DESCRIPTION
**Pull request by asazonova**
fixes #2442 

Reference -> Ref
Package -> Pkg
Group -> Grp
Abstract -> Abst
Virtual -> Virt 
Implementation -> Impl
End to End Flow -> EtE Flow
Specification -> Spec
Property -> Prop
Subcomponent -> Subcomp
Association -> Assoc
Constant -> Const
Propertyset -> Propset

### CODE REVIEW

**Comment by asazonova** [comment]
issue 2443 will have icon decorations, so 2442 is just a shorter label in outline (in my understanding)

**Comment by lwrage** [comment]
2442 is about more descriptive label for flows, not about shorter labels in general

**Comment by lwrage** [comment]
Could you add screenshots of before and after fro a model that has most of these, please? That would make it easier to compare.

**Comment by asazonova** [comment]
issue has been resolved via different branch and PR. this PR is not needed

**Pull request closed without merging**
