### PR TITLE
2478 suppress errors related to missing property sets and ignore selected annexes

### LINKED ISSUE #2288: Configuration flag for deactivating an annex
In some cases, one may want to deactivate an annex from the regular parsing phase. For instance apply analyses that do not depend on them

One may imagine a configuration parameter for that, that would simply deactivate the corresponding registered parser

An open question could be: how about analysis? We could have a warning if EMV2 is disabled when trying to run FHA or FTA

### LINKED ISSUE #2478: Add option to suppress errors related to missing property sets
##  Summary

Models that depend on a contributed property set will have errors if the contributing plugin is not installed.
It should be configurable to suppress such errors. 

Optionally allow the user to enter names of property sets to ignore.

## Environment

* **OSATE Version**: 2.8.0
* **Operating System**: all

### PR DESCRIPTION
**Pull request by asazonova**
fixes #2288 ignore selected annexes
fixes #2478 suppress errors for missing property sets

this PR should replace the [PR 2577](https://github.com/osate/osate2/pull/2577)

### CODE REVIEW

**Comment by asazonova** [comment]
@AaronGreenhouse I added aadl file examples for both annex and property set parts in help to better describe what these features represent. Also added a check for 'with MILS' clause to follow the ignore setting as well for property sets

**Comment by lwrage** [comment]
About image files: There's a mixture of jpeg and png files. I assume most are screen shots, so png should generally be the better option. Also, some are *.jpg, some are *.jpeg. Please use the same extension for all jpeg files.

**Comment by AaronGreenhouse** [comment]
> @AaronGreenhouse I added aadl file examples for both annex and property set parts in help to better describe what these features represent. Also added a check for 'with MILS' clause to follow the ignore setting as well for property sets

Changes to the help file look good, and actually work for me now. 

Hiding the error on the "with " clause works.

**One problem**: names are not case-sensitive in AADL.  Your check currently is case sensitive.  If I suppress `MILS`, but have 

```
			mils::bob => 1;
			MILS::fred => 2;
			MiLs::harry => 3;
```

then only the error on `fred` is supressed.

**Comment by asazonova** [comment]
@AaronGreenhouse images have been replaced with PNGs

**Comment by lwrage** [comment]
I'm wondering if it makes sense to always show a warning at the `with` clause for a ignored property set. Thoughts @AaronGreenhouse @asazonova ?
Also, is there, or should there be, a warning on suppressed annex subclauses/libraries?

**Comment by asazonova** [comment]
> I'm wondering if it makes sense to always show a warning at the `with` clause for a ignored property set. Thoughts @AaronGreenhouse @asazonova ?

I have mixed feelings about this one. On one hand, alert on 'with' clause could serve as a reminder that specific annex needs imported. On the other hand, if you truly do not care to see any errors/alerts about specific annex, wouldn't you want to eliminate those completely from the remaining ones?

**Comment by asazonova** [comment]
> Also, is there, or should there be, a warning on suppressed annex subclauses/libraries?

I'm a minimalist, so I'm in favor of less is more (not having warnings, hopefully since it is advanced feature, users will know what they are doing) 

@jjhugues do you have any strong opinions on this since you created this request?

**Comment by AaronGreenhouse** [comment]
> > Also, is there, or should there be, a warning on suppressed annex subclauses/libraries?
> 
> I'm a minimalist, so I'm in favor of less is more (not having warnings, hopefully since it is advanced feature, users will know what they are doing)
> 
> @jjhugues do you have any strong opinions on this since you created this request?

I agree with Anna here.  I think turning off warnings/errors should do just that.  IT shouldn't cause another warning that the warnings are turned off...

**Comment by jjhugues** [comment]
I agree a warning would be strange here; but I would rather have an info message that says things have been turned off; and that the user might need to install additional plug-ins that have this property set or annex mechanism.

If not, we leave the user ignorant that some portions of the model are not processed.

**Comment by lwrage** [comment]
Info would be fine, too (assuming we can do that in the validator). For property sets I'd like the option to see some message at the `with` clause (as a reminder) but not for each property association.
IIRC, in OSATE <= 2.9.1 we simply ignore annexes if no corresponding plugin is installed without any message.

**Comment by jjhugues** [comment]
I agree an info message for the `with` is enough.

**Comment by asazonova** [comment]
@lwrage Should predeclared property sets be allowed in ignored list?

**Comment by lwrage** [comment]
Predeclared should not be allowed as ignored. Don't add an "all" option.
If info doesn't work, use warning in `with`. Always add the warning in `with` if the property set is ignored.

**Comment by asazonova** [comment]
@AaronGreenhouse ready for review

**Comment by AaronGreenhouse** [comment]
Looks good.

**Review by AaronGreenhouse — APPROVED** [review]
Code looks good.  Help files work.  Functionality is okay.

**Comment by asazonova** [comment]
Test file

package testImagesNew

public
	with sei;
	
	abstract A
		features
			inputSignals: in feature group; -- can add more features here , port, bus access
			InPort: in data port;
			OutPort: out data port;
	end A;
	
	abstract implementation A.i
	end A.i;
	
	bus b
	end b;
	
	bus implementation b.i
		prototypes
			djdk: abstract;
			bp: bus b;
			dp: data dddd;
			hdskf: device;
			memp: memory mem;
			pp: process p;
			prp: processor pr;
	end b.i;

	data dddd
	end dddd;

	data d
	end d;
	
	data implementation d.i
	end d.i;
	
	device de
		features
			power: in feature A;
			canbusaccess: requires bus access b;
			actuatorin: in data port d;
			speed: out data port d;
		flows
			f0: flow source speed;
	end de;
	
	device implementation de.i	
		flows
			f0: flow source speed;
	end de.i;
	
	memory mem	
	end mem;

	memory implementation mem.i
	end mem.i;
	
	process p
	end p;
	
	process implementation p.i
	end p.i;
	
	processor pr
		features
			f: in feature A;
	end pr;
	
	processor implementation pr.i
	end pr.i;

	subprogram sbp
		features
			p: in parameter;
			o: out parameter;
			n: out event port;
	end sbp;
	
	system sys
		features
			inDataPort: in data port;
			outDataPort: out data port d;
		flows
			flowsource: flow source outDataPort {Latency => 1ms .. 1ms;};
			flowsink: flow sink inDataPort;
			flowpath: flow path inDataPort -> outDataPort;
		annex EMV2 {**
		**};
	end sys;
	
	system implementation sys.i
		subcomponents
			as: abstract A;
			bs: bus b;
			dd: data dddd;
			ds: device de;
			ms: memory mem;
			hw: system sys;
			ps: process p;
			prs: processor pr;
		flows
			flow1: end to end flow de.f0 -> SCS.data3;
	end sys.i;
	
	system ElectricGrid
	features
			Supplier: in feature A;
			Consumer: out feature A;
		flows
			flowsource: flow source Consumer {Latency => 1ms .. 1ms;};
			flowsink: flow sink Supplier;
			flowpath: flow path Supplier -> Consumer;
		properties
			SEI::GrossWeight => 0.9kg;
			SEI::PowerCapacity => 40.0W;
	end ElectricGrid;
	
	system implementation ElectricGrid.i
		flows
			flowsource: flow source Consumer {Latency => 1ms .. 1ms;};
			flowsink: flow sink Supplier;
			flowpath: flow path Supplier -> Consumer;
	end ElectricGrid.i;
	
	system SCS
		features
			power: in feature A;
		properties
			SEI::PowerBudget => 2.5w applies to power;
			SEI::WeightLimit => 2.5kg;
	end SCS;

	system implementation SCS.tier0
		subcomponents
			dcs: system DCS.singletier0;
			actuator: device de;
		connections
			p1: feature power -> dcs.power;
			cb3: bus access dcs.canbusaccess <-> actuator.canbusaccess;
			data3: feature dcs.actuatorOut -> actuator.actuatorin;
	end SCS.tier0;
	
	feature group sensorInputs
		features
			--provided:out event data port;
			required: in event data port d;
	end sensorInputs;
	
	system DCS
		features
			power: in feature A;
			canbusaccess: provides bus access b;
			actuatorOut: out data port d;
			receiveInput: in feature group sensorInputs;
	end DCS;

	system implementation DCS.singletier0
		subcomponents
			dca: system DCA;
			hw: system platform;
			simpleSensor: abstract A.i;
		connections
			p1: feature power -> hw.power;
			data3: port dca.actuatorOut -> actuatorOut;
			c0: feature group receiveInput -> simpleSensor.inputSignals;
	end DCS.singletier0;
	
	system platform
		features
			canbusaccess: provides bus access b;
			power: in feature A;
		properties
			SEI::PowerBudget => 0.8w applies to power;
			SEI::MIPSCapacity => 2.4 mips;		
	end platform;
	
	system DCA
		features
			actuatorOut: out data port d;
		properties
			SEI::MIPSBudget => 2.0 mips;
	end DCA;

end testImagesNew;

**Pull request merged**
