### PR TITLE
Make inModesAndTransitions not transient

### LINKED ISSUE #1493: Setting a modal path to in-mode does not reflect change
## Summary
When setting a modal path to **in-mode** using the graphical editor **AADL** properties view, no change occurs.  The in-mode looks like it is set and then removed simultaneously.
We suspect it has something to do with the latest changes made for #1449.

## Steps to Reproduce

1. Create type classifier
2. Create mode, feature, and flow spec
3. Select the flow spec
4. Open properties view
5. Click the mode in the in-mode section

```aadl
package Test
public
	abstract t
		features
			feat: in feature;
		flows
			f_sink: flow sink feat;
		modes
			m1: mode;
	end t;
end Test;
```

## Environment

* **OSATE Version**: 2.3.5 Release
* **Operating System**: Windows 10

### PR DESCRIPTION
**Pull request by lwrage**
fixes #1493 
@Etienne13 Could you check if this also fixes bug #1551, please?

### CODE REVIEW

**Comment by Etienne13** [comment]
@lwrage I just tried with the current version (2018-10-01 23:17) on the testing update site (https://osate-build.sei.cmu.edu/download/osate/testing/updates/) but issue #1551 persists on this version.

**Comment by lwrage** [comment]
@Etienne13 We create and test pull requests before they are integrated into the nightly build. To test this you need to pull in the latest sources, switch to the branch for this pull request (origin/1493_remove_transient_setting) and run from the development environment.

**Comment by Etienne13** [comment]
@lwrage I tried with sources but had compilation issues due to missing dependencies in my configuration of Eclipse... So I move to the update-site. I will try again with sources asap.

**Comment by Etienne13** [comment]
@lwrage do you have a description of the eclipse settings, or a procedure to follow to setup eclipse and have the latest version of osate sources compile? I am still having plenty of compilation errors. The one I could trace is : "com.itemis.xtext.testing is missing" and I guess it is the reason why other xtext-based projects do not build as well...

**Comment by lwrage** [comment]
@Etienne13 see http://osate.org/setup-development.html

**Comment by Etienne13** [comment]
@lwrage thanks a lot for the pointer; I could finally test and the issue ##1551 is indeed fixed in 1493_remove_transient_setting

**Comment by Etienne13** [comment]
Ooops, sorry for closing the PR, mistak in using the interface.

**Pull request merged**
