### PR TITLE
Support for mode switch transitions in BA

### PR DESCRIPTION
**Pull request by Etienne13**

### CODE REVIEW

**Comment by lwrage** [comment]
Can you add a JUnit test for #2147, please?

**Comment by Etienne13** [comment]
It is present in the first commit

**Comment by lwrage** [comment]
I have no idea how I missed that,,,

**Comment by lwrage** [comment]
@jjhugues Could you review this, please. It should fix #2146 and #2147.

**Comment by jjhugues** [comment]
@Etienne13 , this patch addresses #2146 and #2147 but I miss a test for mode transitions.
I would have expected a test that uses AADL core mode, is that correct?

**Comment by Etienne13** [comment]
@jjhugues , this is a good question, and I was not completely sure on how to proceed. In BA, transitions triggered by in event [data] ports in "non-dispatchable" components aim at refining mode transitions. However, I was not sure whether I should enforce this in the BA plugin or not. By enforcing it, the plugin becomes more rigorous and less flexible. Enforcing the constraint would be consistent with the way the plugin is implemented for the other parts of the standard.

What do you think?

**Comment by jjhugues** [comment]
@Etienne13 , I was pointing at a more simple issue: I see no test with modes that would test the code you added for modes. Did I miss it? You added two tests for other issues that this PR closes

**Comment by lwrage** [comment]
@Etienne13 If this PR does more than fix 2146 and 2147, could you create an issue for that, please?

**Comment by Etienne13** [comment]
@jjhugues I did not add code for modes per se, but I added code for supporting transitions in BA which refine mode transitions from the core standard. This is the fix for #2147, where in event [data] ports are used in transition conditions. The only situation I know of that would allow this is when the source state is a mode (the state has the same identifier as a mode of the enclosing component).

To be more consistent, I added a mode in the test case for issue #2147. This way the AADL model actually covers the type of models covered by the fix.

@lwrage ok, I will open an issue to enforce the input state of such transitions (see comments above) has the same identifier as a mode of the enclosing component.

**Comment by jjhugues** [comment]
@Etienne13 , can you either update this PR or close it and do a new one? The test for Issue 2417 is failing

**Pull request merged**
